version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresCont
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fund_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cathbybk-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cathbybk-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fund_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres

volumes:
  postgres_data: